---
- name: configure keepalived
  ansible.builtin.template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    mode: "0640"
    validate: keepalived --config-test --use-file=%s
  tags: keepalived
  become: yes
  notify: restart keepalived

#dedicated logfile
- name: Dedicated logfile if keepalived_logfile is defined
  block:
    - name: Set logfacility 6 in keepalived options
      replace:
        path: /etc/sysconfig/keepalived
        regexp: '^KEEPALIVED_OPTIONS=.*$'
        replace: 'KEEPALIVED_OPTIONS="-D --log-facility=6"'
      notify: restart keepalived

    - name: Rsyslog conf for keepalived
      copy:
        content: "local6.* {{ keepalived_logfile }}"
        dest: "/etc/rsyslog.d/keepalived.conf"
        owner: "root"
        group: "root"
        mode: 0644
      notify: restart rsyslog

    - name: Logrotate conf for keepalived
      template:
        src: "keepalived.logrotate.j2"
        dest: "/etc/logrotate.d/keepalived"
        owner: "root"
        group: "root"
        mode: 0644

  when: keepalived_logfile is defined
  
- name: Check if keepalived is enabled
  ansible.builtin.shell: "systemctl daemon-reload && systemctl is-enabled {{ keepalived_service_name }}"
  register: isenabled
  changed_when: (isenabled.stdout == "disabled" or isenabled.stdout == "masked") and isenabled.rc != 0
  failed_when: (isenabled.stdout != "disabled" and isenabled.stdout != "masked") and isenabled.rc != 0
  tags: skip_ansible_lint
  
- name: Enable service keepalived if disabled
  ansible.builtin.service:
    name: keepalived
    enabled: yes
    masked: no
  when:
    - isenabled is changed